name: Jessica
version: 1.0
main: de.d3adspace.jessica.spigot.plugin.JessicaSpigotPlugin
website: https://www.felix-klauke.de

author: Felix Klauke

load: STARTUP

soft-depend: [ Vault ]

commands:
  permissions:
    description: The general permissions command
    aliases: [ "perms", "perm", "gm", "pex", "permission" ]
    usage: /permissions