name: Jessica
version: 1.0
main: de.d3adspace.jessica.spigot.plugin.JessicaSpigotPlugin

author: Felix Klauke

load: STARTUP

soft-depend: [ Vault ]

commands:
  perm:
    description: The general permissions command
    aliases: [ "gm", "pex", "permissions" ]
    usage: /perm